apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: react-ui
  template:
    metadata:
      labels:
        app: react-ui
        service: react-ui
    spec:
      containers:
        - name: react-ui
          image: vermavarun/react-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
          # env:
          #   - name: ASPNETCORE_URLS
          #     value: http://+:80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
